// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: friends.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const acceptFriend = `-- name: AcceptFriend :one
UPDATE friends
SET accepted = true
WHERE user_id = $1 AND friend_id = $2
RETURNING id, user_id, friend_id, created_at, accepted
`

type AcceptFriendParams struct {
	UserID   uuid.NullUUID
	FriendID uuid.NullUUID
}

func (q *Queries) AcceptFriend(ctx context.Context, arg AcceptFriendParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, acceptFriend, arg.UserID, arg.FriendID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.CreatedAt,
		&i.Accepted,
	)
	return i, err
}

const addFriend = `-- name: AddFriend :one
INSERT INTO friends (user_id, friend_id) 
VALUES ($1, $2)
RETURNING id, user_id, friend_id, created_at, accepted
`

type AddFriendParams struct {
	UserID   uuid.NullUUID
	FriendID uuid.NullUUID
}

func (q *Queries) AddFriend(ctx context.Context, arg AddFriendParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, addFriend, arg.UserID, arg.FriendID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.CreatedAt,
		&i.Accepted,
	)
	return i, err
}

const getFriendRequests = `-- name: GetFriendRequests :many
SELECT id, user_id, friend_id, created_at, accepted FROM friends WHERE friend_id = $1 AND accepted = false
`

func (q *Queries) GetFriendRequests(ctx context.Context, friendID uuid.NullUUID) ([]Friend, error) {
	rows, err := q.db.QueryContext(ctx, getFriendRequests, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friend
	for rows.Next() {
		var i Friend
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.CreatedAt,
			&i.Accepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriends = `-- name: GetFriends :many
SELECT id, user_id, friend_id, created_at, accepted FROM friends WHERE user_id = $1 AND accepted = true
OR friend_id = $1 AND accepted = true
`

func (q *Queries) GetFriends(ctx context.Context, userID uuid.NullUUID) ([]Friend, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friend
	for rows.Next() {
		var i Friend
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.CreatedAt,
			&i.Accepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFreind = `-- name: RemoveFreind :one
DELETE FROM friends WHERE user_id = $1 AND friend_id = $2
RETURNING id, user_id, friend_id, created_at, accepted
`

type RemoveFreindParams struct {
	UserID   uuid.NullUUID
	FriendID uuid.NullUUID
}

func (q *Queries) RemoveFreind(ctx context.Context, arg RemoveFreindParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, removeFreind, arg.UserID, arg.FriendID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.CreatedAt,
		&i.Accepted,
	)
	return i, err
}
