// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages_paginated.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getGroupMessagesPaginated = `-- name: GetGroupMessagesPaginated :many
SELECT
    m.message_id,
    m.content,
    m.created_at,
    u_from.username as from_username,
    g.name as group_name
FROM messages m
JOIN users u_from ON m.from_user_id = u_from.id
JOIN groups g ON m.group_id = g.id
WHERE
    m.is_group = TRUE AND m.group_id = $1 AND m.created_at < $2
ORDER BY m.created_at DESC
LIMIT $3
`

type GetGroupMessagesPaginatedParams struct {
	GroupID   uuid.NullUUID
	CreatedAt time.Time
	Limit     int32
}

type GetGroupMessagesPaginatedRow struct {
	MessageID    string
	Content      string
	CreatedAt    time.Time
	FromUsername string
	GroupName    string
}

func (q *Queries) GetGroupMessagesPaginated(ctx context.Context, arg GetGroupMessagesPaginatedParams) ([]GetGroupMessagesPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMessagesPaginated, arg.GroupID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMessagesPaginatedRow
	for rows.Next() {
		var i GetGroupMessagesPaginatedRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.CreatedAt,
			&i.FromUsername,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBetweenUsersPaginated = `-- name: GetMessagesBetweenUsersPaginated :many
SELECT
    m.message_id,
    m.content,
    m.created_at,
    u_from.username as from_username,
    u_to.username as to_username
FROM messages m
JOIN users u_from ON m.from_user_id = u_from.id
JOIN users u_to ON m.to_user_id = u_to.id
WHERE
    m.is_group = FALSE AND (
        (u_from.username = $1 AND u_to.username = $2) OR
        (u_from.username = $2 AND u_to.username = $1)
    ) AND m.created_at < $3
ORDER BY m.created_at DESC
LIMIT $4
`

type GetMessagesBetweenUsersPaginatedParams struct {
	Username   string
	Username_2 string
	CreatedAt  time.Time
	Limit      int32
}

type GetMessagesBetweenUsersPaginatedRow struct {
	MessageID    string
	Content      string
	CreatedAt    time.Time
	FromUsername string
	ToUsername   string
}

func (q *Queries) GetMessagesBetweenUsersPaginated(ctx context.Context, arg GetMessagesBetweenUsersPaginatedParams) ([]GetMessagesBetweenUsersPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBetweenUsersPaginated,
		arg.Username,
		arg.Username_2,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBetweenUsersPaginatedRow
	for rows.Next() {
		var i GetMessagesBetweenUsersPaginatedRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.CreatedAt,
			&i.FromUsername,
			&i.ToUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
