// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    message_id,
    from_user_id,
    to_user_id,
    content,
    is_group,
    group_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, message_id, from_user_id, to_user_id, group_id, content, is_group, created_at
`

type CreateMessageParams struct {
	MessageID  string
	FromUserID uuid.UUID
	ToUserID   uuid.NullUUID
	Content    string
	IsGroup    sql.NullBool
	GroupID    uuid.NullUUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.MessageID,
		arg.FromUserID,
		arg.ToUserID,
		arg.Content,
		arg.IsGroup,
		arg.GroupID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FromUserID,
		&i.ToUserID,
		&i.GroupID,
		&i.Content,
		&i.IsGroup,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesBetweenUsers = `-- name: GetMessagesBetweenUsers :many
SELECT
    m.message_id,
    m.content,
    m.created_at,
    u_from.username as from_username,
    u_to.username as to_username
FROM messages m
JOIN users u_from ON m.from_user_id = u_from.id
JOIN users u_to ON m.to_user_id = u_to.id
WHERE
    (u_from.username = $1 AND u_to.username = $2) OR
    (u_from.username = $2 AND u_to.username = $1)
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $4
`

type GetMessagesBetweenUsersParams struct {
	Username   string
	Username_2 string
	Limit      int32
	Offset     int32
}

type GetMessagesBetweenUsersRow struct {
	MessageID    string
	Content      string
	CreatedAt    time.Time
	FromUsername string
	ToUsername   string
}

func (q *Queries) GetMessagesBetweenUsers(ctx context.Context, arg GetMessagesBetweenUsersParams) ([]GetMessagesBetweenUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBetweenUsers,
		arg.Username,
		arg.Username_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBetweenUsersRow
	for rows.Next() {
		var i GetMessagesBetweenUsersRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.CreatedAt,
			&i.FromUsername,
			&i.ToUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
