// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Friend struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	FriendID  uuid.NullUUID
	CreatedAt time.Time
	Accepted  bool
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Icon        sql.NullString
	CustomIcon  sql.NullString
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMember struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	Role         string
	PasswordHash string
	Icon         sql.NullString
	CustomIcon   sql.NullString
}
