// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, icon, custom_icon)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, username, role, password_hash, icon, custom_icon
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Icon         sql.NullString
	CustomIcon   sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Icon,
		arg.CustomIcon,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Icon,
		&i.CustomIcon,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1
RETURNING id, created_at, updated_at, username, role, password_hash, icon, custom_icon
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Icon,
		&i.CustomIcon,
	)
	return i, err
}

const getAllUsernames = `-- name: GetAllUsernames :many
SELECT username FROM users
`

func (q *Queries) GetAllUsernames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, username, role, password_hash, icon, custom_icon FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Icon,
		&i.CustomIcon,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, username, role, password_hash, icon, custom_icon FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Icon,
		&i.CustomIcon,
	)
	return i, err
}

const getUsersByUsernames = `-- name: GetUsersByUsernames :many
SELECT id, created_at, updated_at, username, role, password_hash, icon, custom_icon FROM users WHERE username = ANY($1::text[])
`

func (q *Queries) GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByUsernames, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Role,
			&i.PasswordHash,
			&i.Icon,
			&i.CustomIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, updated_at = NOW(), icon = $3, custom_icon = $4
WHERE id = $1
RETURNING id, created_at, updated_at, username, role, password_hash, icon, custom_icon
`

type UpdateUserParams struct {
	ID         uuid.UUID
	Username   string
	Icon       sql.NullString
	CustomIcon sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Icon,
		arg.CustomIcon,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Icon,
		&i.CustomIcon,
	)
	return i, err
}
